### train configuraton

exp_dir: exp/samresnet100_50
gpus: "[2,3,4,5,6]"
num_avg: 1
enable_amp: False # whether enable automatic mixed precision training

seed: 42
num_epochs: 20
save_epoch_interval: 1 # save model every epoch
log_batch_interval: 100 # log every 100 batchs

dataloader_args:
  batch_size: 64
  num_workers: 8
  pin_memory: False
  prefetch_factor: 8
  drop_last: True

dataset_args:
  # the sample number which will be traversed within one epoch, if the value equals to 0,
  # the utterance number in the dataset will be used as the sample_num_per_epoch.
  sample_num_per_epoch: 0
  shuffle: True
  shuffle_args:
    shuffle_size: 2500
  filter: True
  filter_args:
    min_num_frames: 20
    max_num_frames: 800
  resample_rate: 16000
  speed_perturb: True
  num_frms: 50
  aug_prob: 0.6 # prob to add reverb & noise aug per sample
  fbank_args:
    num_mel_bins: 80
    frame_shift: 10
    frame_length: 25
    dither: 1.0
  spec_aug: False
  spec_aug_args:
    num_t_mask: 1
    num_f_mask: 2
    max_t: 5
    max_f: 8
    prob: 0.35

model: SimAM_ResNet100_ASP # ResNet18, ResNet34, ResNet50, ResNet101, ResNet152
model_init: null
model_args:
  embed_dim: 256
projection_args:
  project_type: "arc_margin" # add_margin, arc_margin, sphere, sphereface2, softmax, arc_margin_intertopk_subcenter
  scale: 32.0
  easy_margin: False

margin_scheduler: MarginScheduler
margin_update:
  initial_margin: 0.2
  final_margin: 0.2
  increase_start_epoch: 1
  fix_start_epoch: 1
  update_margin: True
  increase_type: "exp" # exp, linear

loss: CrossEntropyLoss
loss_args: {}

optimizer: SGD
optimizer_args:
  momentum: 0.9
  nesterov: True
  weight_decay: 0.0001

scheduler: ExponentialDecrease
scheduler_args:
  initial_lr: 0.001
  final_lr: 0.00025
  warm_up_epoch: 1
  warm_from_zero: True